### ISSUE TITLE
Waiter Number of Staff who is handling the order

### ISSUE THREAD

**Issue by rsj30** [foodcart/coursework2#1]
Hey guys!

On the "Order Status" pane,  can we add the waiter number of the staff who handles each order ? It will be clearer to the user to see who is handling what. I know there is separate Waiter Panel that shows what each waiter is doing but I just thought it can be good to display the waiter number to the user.

Regards,
Rohit Jamwal
H00139801
Msc Data Science

**Comment by Lamiv** [comment]
Hi, added new column to Status Table that shows Waiter ID

**Comment by rsj30** [comment]
Thanks Vimal
